{% set name = "bmad" %}
{% set version = "20211214-1" %}
{% set major = version.split("-")[0] %}
{% set minor = version.split("-")[1] %}

package:
  name: {{ name|lower }}
  version: {{ version | replace("-", ".") }}

source:
  url: https://github.com/bmad-sim/bmad_distribution/releases/download/{{ version }}/bmad_dist_{{ major[:-4] }}_{{ major[-4:] }}-{{ minor }}.tgz
  sha256: bd2d3031246da9d0be268a50b696801740be22dddc13f68f7531340458899d6a

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - cmake
    - make
    - automake
    - autoconf
    - libtool
    - m4
    - pkg-config
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - readline
    - ncurses
    - cairo
    - pango
    - xorg-libxt
    - pgplot
    - hdf5
    - xorg-libx11
    - xorg-xproto
    - fftw
    - libblas
    - liblapack
    - lapack95
    - gsl ==2.6
    - fgsl
    - xraylib
  run:
    - readline
    - ncurses
    - cairo
    - pango
    - xorg-libxt
    - pgplot
    - hdf5
    - fftw
    - libblas
    - liblapack
    - lapack95
    - gsl ==2.6
    - fgsl
    - xraylib
    - xorg-libx11
    - xorg-xproto
    - libopenblas
    - libcblas

test:
  commands:
    - tao -help

about:
  home: https://www.classe.cornell.edu/bmad
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: bmad/Copyright
  summary: Bmad is an object oriented, open source, subroutine library for relativistic charged-particle dynamics simulations in accelerators and storage rings.
  description: |
    Bmad has been developed at Cornell University's Laboratory for Elementary
    Particle Physics and has been in use since the mid 1990s.
    Bmad has a wide range of routines to do many things.
    Bmad can be used to study both single and multi-particle
    beam dynamics. It has routines to track both particles and
    macroparticles. Bmad has various tracking algorithms including
    Runge-Kutta and symplectic (Lie algebraic) integration.
    Wakefields, and radiation excitation and damping can be simulated.
    Bmad has routines for calculating transfer matrices, emittances,
    Twiss parameters, dispersion, coupling, etc.
  doc_url: https://www.classe.cornell.edu/bmad/manual.html

extra:
  recipe-maintainers:
    - hhslepicka
    - ChristopherMayes
